/*
 *
 *    Copyright (c) 2020-2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//! Native Rust implementation of the Matter protocol by CSA-IOT.
//!
//! This crate implements the Matter specification that can be run on embedded devices
//! to build Matter-compatible smart-home/IoT devices.
//!
//! Look at the examples project in the workspace for example applications built using this crate, and the tests directory for unit tests.
//!
//! Start off exploring by going to the [Matter] object.
#![cfg_attr(not(feature = "std"), no_std)]
#![allow(async_fn_in_trait)]
#![allow(unknown_lints)]
#![allow(clippy::uninlined_format_args)]
#![recursion_limit = "1024"]

use core::future::Future;

use crate::crypto::Crypto;
use crate::dm::clusters::basic_info::{BasicInfoConfig, BasicInfoSettings};
use crate::dm::clusters::dev_att::DeviceAttestation;
use crate::dm::ChangeNotify;
use crate::error::{Error, ErrorCode};
use crate::fabric::Fabrics;
use crate::failsafe::FailSafe;
use crate::im::{AttrId, ClusterId, EndptId};
use crate::pairing::qr::{
    no_optional_data, CommFlowType, NoOptionalData, Qr, QrPayload, QrTextType,
};
use crate::pairing::DiscoveryCapabilities;
use crate::persist::KvBlobStore;
use crate::sc::pase::spake2p::{Spake2pVerifierPassword, SPAKE2P_VERIFIER_SALT_ZEROED};
use crate::sc::pase::Pase;
use crate::transport::network::{NetworkMulticast, NetworkReceive, NetworkSend};
use crate::transport::session::Sessions;
use crate::transport::{
    PacketBufferExternalAccess, Transport, TransportRunner, MAX_RX_BUF_SIZE, MAX_TX_BUF_SIZE,
};
use crate::utils::cell::RefCell;
use crate::utils::epoch::Epoch;
use crate::utils::init::{init, Init};
use crate::utils::storage::pooled::BufferAccess;
use crate::utils::storage::WriteBuf;
use crate::utils::sync::blocking::Mutex;
use crate::utils::sync::Notification;

use rand_core::RngCore;

/// Re-export the `rs_matter_macros::import` proc-macro
pub use rs_matter_macros::import;

#[cfg(feature = "alloc")]
extern crate alloc;

// This mod MUST go first, so that the others see its macros.
pub(crate) mod fmt;

pub mod acl;
pub mod cert;
pub mod commissioner;
pub mod credentials;
pub mod crypto;
pub mod dm;
pub mod error;
pub mod fabric;
pub mod failsafe;
pub mod group_keys;
pub mod im;
pub mod pairing;
pub mod persist;
pub mod respond;
pub mod sc;
pub mod tlv;
pub mod transport;
pub mod utils;

/// Re-export several crates
///
/// This is necessary for crates used in the code generated by the proc-macros
pub mod reexport {
    pub use bitflags;
    #[cfg(feature = "defmt")]
    pub use defmt;
    #[cfg(feature = "log")]
    pub use log;
    pub use strum;
}

#[cfg(feature = "alloc")]
#[macro_export]
macro_rules! alloc {
    ($val:expr) => {
        alloc::boxed::Box::new($val)
    };
}

#[cfg(not(feature = "alloc"))]
#[macro_export]
macro_rules! alloc {
    ($val:expr) => {
        $val
    };
}

/// The Matter UDP port
pub const MATTER_PORT: u16 = 5540;

/// The maximum length of a Matter mDNS service name
pub const MATTER_SERVICE_MAX_NAME_LEN: usize = 33;

/// A type capturing all the information necessary to publish a commissioned
/// Matter fabric or a non-commissioned Matter instance over mDNS.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum MatterMdnsService {
    /// A commissioned Matter service for a particular fabric
    ///
    /// The published name is in the form `<compressed-fabric-id-hex>-<node-id-hex>`.
    Commissioned {
        compressed_fabric_id: u64,
        node_id: u64,
    },
    /// A non-commissioned Matter service
    ///
    /// The published name is in the form `<id-hex>`. The discriminator should be used as an mDNS TXT entry
    Commissionable {
        id: u64,
        /// The discriminator to be communicated over mDNS
        discriminator: u16,
    },
}

impl MatterMdnsService {
    /// Return the name of the mDNS service in a buffer
    ///
    /// NOTE: The buffer needs to be at least `MATTER_SERVICE_MAX_NAME_LEN` bytes long
    /// or else this method will panic.
    pub fn name<'a>(&self, buf: &'a mut [u8]) -> &'a str {
        use core::fmt::Write;

        match self {
            Self::Commissioned {
                compressed_fabric_id,
                node_id,
            } => {
                if buf.len() < MATTER_SERVICE_MAX_NAME_LEN {
                    panic!("Buffer too small for mDNS service name");
                }

                let mut wb = WriteBuf::new(buf);

                write_unwrap!(&mut wb, "{:016X}", compressed_fabric_id);

                unwrap!(wb.append(b"-"));

                write_unwrap!(&mut wb, "{:016X}", node_id);

                let len = wb.get_tail();

                unwrap!(
                    core::str::from_utf8(&buf[..len]),
                    "Invalid UTF-8 in mDNS service name"
                )
            }
            Self::Commissionable { id, .. } => {
                if buf.len() < 16 {
                    panic!("Buffer too small for mDNS service name");
                }

                let mut wb = WriteBuf::new(buf);

                write_unwrap!(&mut wb, "{:016X}", id);

                let len = wb.get_tail();

                unwrap!(
                    core::str::from_utf8(&buf[..len]),
                    "Invalid UTF-8 in mDNS service name"
                )
            }
        }
    }
}

/// Device basic commissioning data
#[derive(Debug, Clone)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct BasicCommData {
    /// The password which is necessary to authenticate the device in either
    /// initial commissioning, or when the basic commissioning window is opened
    pub password: Spake2pVerifierPassword,
    /// The 12-bit discriminator used to differentiate between multiple devices
    pub discriminator: u16,
}

/// The primary Matter Object
pub struct Matter<'a> {
    /// The internal state of the Matter Object, protected by a mutex for concurrent access from different threads and async tasks.
    state: Mutex<RefCell<MatterState>>,
    /// The transport state of the Matter Object
    ///
    /// Public for unit tests
    pub transport: Transport,
    /// A notification that the Matter mDNS services might have changed
    mdns_changed: Notification,
    /// A notification that a session had been removed
    session_removed: Notification,
    /// A notification that the groups have been modified
    groups_modified: Notification,
    /// The function to get the current epoch time in milliseconds
    epoch: Epoch,
    /// The basic information configuration for this Matter device
    dev_det: &'a BasicInfoConfig<'a>,
    /// The basic commissioning data for this Matter device
    dev_comm: BasicCommData,
    /// The device attestation data fetcher for this Matter device
    dev_att: &'a dyn DeviceAttestation,
    /// The port number on which the Matter stack will listen for incoming connections
    port: u16,
}

impl<'a> Matter<'a> {
    /// Create a new Matter object when support for the Rust Standard Library is enabled.
    ///
    /// # Parameters
    /// * dev_det: An object of type [BasicInfoConfig].
    /// * dev_comm: An object of type [BasicCommData]. This object contains the basic commissioning
    ///   data required for the device.
    /// * dev_att: An object that implements the trait [DevAttDataFetcher]. Any Matter device
    ///   requires a set of device attestation certificates and keys. It is the responsibility of
    ///   this object to return the device attestation details when queried upon.
    /// * port: The port number on which the Matter stack will listen for incoming connections.
    #[cfg(feature = "std")]
    #[inline(always)]
    pub const fn new_default(
        dev_det: &'a BasicInfoConfig<'a>,
        dev_comm: BasicCommData,
        dev_att: &'a dyn DeviceAttestation,
        port: u16,
    ) -> Self {
        use crate::utils::epoch::sys_epoch;

        Self::new(dev_det, dev_comm, dev_att, sys_epoch, port)
    }

    /// Create a new Matter object
    ///
    /// # Parameters
    /// * dev_det: An object of type [BasicInfoConfig].
    /// * dev_comm: An object of type [BasicCommData]. This object contains the basic commissioning
    ///   data required for the device.
    /// * dev_att: An object that implements the trait [DevAttDataFetcher]. Any Matter device
    ///   requires a set of device attestation certificates and keys. It is the responsibility of
    ///   this object to return the device attestation details when queried upon.
    /// * epoch: A function of type [Epoch]. This function is responsible for providing the current
    ///   "unix" time in milliseconds
    /// * port: The port number on which the Matter stack will listen for incoming connections.
    #[inline(always)]
    pub const fn new(
        dev_det: &'a BasicInfoConfig<'a>,
        dev_comm: BasicCommData,
        dev_att: &'a dyn DeviceAttestation,
        epoch: Epoch,
        port: u16,
    ) -> Self {
        Self {
            state: Mutex::new(RefCell::new(MatterState::new(epoch))),
            transport: Transport::new(dev_det),
            mdns_changed: Notification::new(),
            session_removed: Notification::new(),
            groups_modified: Notification::new(),
            epoch,
            dev_det,
            dev_comm,
            dev_att,
            port,
        }
    }

    /// Create an in-place initializer for a Matter object
    /// when support for the Rust Standard Library is enabled.
    ///
    /// # Parameters
    /// * dev_det: An object of type [BasicInfoConfig].
    /// * dev_comm: An object of type [BasicCommData]. This object contains the basic commissioning
    ///   data required for the device.
    /// * dev_att: An object that implements the trait [DevAttDataFetcher]. Any Matter device
    ///   requires a set of device attestation certificates and keys. It is the responsibility of
    ///   this object to return the device attestation details when queried upon.
    /// * port: The port number on which the Matter stack will listen for incoming connections.
    #[cfg(feature = "std")]
    pub fn init_default(
        dev_det: &'a BasicInfoConfig<'a>,
        dev_comm: BasicCommData,
        dev_att: &'a dyn DeviceAttestation,
        port: u16,
    ) -> impl Init<Self> {
        use crate::utils::epoch::sys_epoch;

        Self::init(dev_det, dev_comm, dev_att, sys_epoch, port)
    }

    /// Create an in-place initializer for a Matter object
    ///
    /// # Parameters
    /// * dev_det: An object of type [BasicInfoConfig].
    /// * dev_comm: An object of type [BasicCommData]. This object contains the basic commissioning
    ///   data required for the device.
    /// * dev_att: An object that implements the trait [DevAttDataFetcher]. Any Matter device
    ///   requires a set of device attestation certificates and keys. It is the responsibility of
    ///   this object to return the device attestation details when queried upon.
    /// * epoch: A function of type [Epoch]. This function is responsible for providing the current
    ///   "unix" time in milliseconds
    /// * port: The port number on which the Matter stack will listen for incoming connections.
    pub fn init(
        dev_det: &'a BasicInfoConfig<'a>,
        dev_comm: BasicCommData,
        dev_att: &'a dyn DeviceAttestation,
        epoch: Epoch,
        port: u16,
    ) -> impl Init<Self> {
        init!(
            Self {
                state <- Mutex::init(RefCell::init(MatterState::init(epoch))),
                transport <- Transport::init(dev_det),
                mdns_changed: Notification::new(),
                session_removed: Notification::new(),
                groups_modified: Notification::new(),
                epoch,
                dev_det,
                dev_comm,
                dev_att,
                port,
            }
        )
    }

    pub fn initialize_transport_buffers(&self) -> Result<(), Error> {
        self.transport.initialize_buffers()
    }

    pub fn dev_det(&self) -> &BasicInfoConfig<'_> {
        self.dev_det
    }

    pub fn dev_att(&self) -> &dyn DeviceAttestation {
        self.dev_att
    }

    pub fn dev_comm(&self) -> &BasicCommData {
        &self.dev_comm
    }

    pub fn port(&self) -> u16 {
        self.port
    }

    pub fn epoch(&self) -> Epoch {
        self.epoch
    }

    pub fn transport_rx_buffer(&self) -> PacketBufferExternalAccess<'_, MAX_RX_BUF_SIZE> {
        self.transport.rx_buffer()
    }

    pub fn transport_tx_buffer(&self) -> PacketBufferExternalAccess<'_, MAX_TX_BUF_SIZE> {
        self.transport.tx_buffer()
    }

    /// A utility method to replace the initial Device Attestation with another one.
    pub fn replace_dev_att(&mut self, dev_att: &'a dyn DeviceAttestation) {
        self.dev_att = dev_att;
    }

    /// Print the standard QR code text to the console
    ///
    /// The printed QR code text corresponds to the standard commissioning flow (i.e. `CommFlowType::Standard`)
    /// and contains no optional data.
    ///
    /// This method is useful primarily during development, when the Matter device is
    /// attached to a console. It is expected that the developer will call this method prior to running the Matter transport.
    ///
    /// # Arguments
    /// - `disc_caps`: The discovery capabilities to be used in the QR code payload
    pub fn print_standard_qr_text(&self, disc_caps: DiscoveryCapabilities) -> Result<(), Error> {
        let rx_buf = self.transport.rx_buffer();

        let mut buf = rx_buf.get_immediate().ok_or(ErrorCode::NoMemory)?;
        let buf = &mut *buf;

        let payload = self.standard_qr_payload(disc_caps)?;

        let (text, _) = payload.as_str(buf)?;

        // Do not remove this logging line or change its formatting.
        // C++ E2E tests rely on this log line to grep the QR code
        info!("SetupQRCode: [{}]", text);

        Ok(())
    }

    /// Print the standard QR code to the console
    ///
    /// The printed QR code corresponds to the standard commissioning flow (i.e. `CommFlowType::Standard`)
    /// and contains no optional data.
    ///
    /// This method is useful primarily during development, when the Matter device is
    /// attached to a console. It is expected that the developer will call this method prior to running the Matter transport.
    ///
    /// # Arguments
    /// - `text_type`: The type of text representation to use when printing the QR code
    /// - `disc_caps`: The discovery capabilities to be used in the QR code payload
    pub fn print_standard_qr_code(
        &self,
        text_type: QrTextType,
        disc_caps: DiscoveryCapabilities,
    ) -> Result<(), Error> {
        // Also print the pairing code for convenience
        info!(
            "PairingCode: [{}]",
            self.dev_comm.compute_pretty_pairing_code()
        );

        let rx_buf = self.transport.rx_buffer();

        let mut buf = rx_buf.get_immediate().ok_or(ErrorCode::NoMemory)?;
        let buf = &mut *buf;

        let payload = self.standard_qr_payload(disc_caps)?;

        let (text, buf) = payload.as_str(buf)?;

        let (tmp_buf, out_buf) = buf.split_at_mut(buf.len() / 2);

        let qr = Qr::compute(text, tmp_buf, out_buf)?;

        const BORDER_SIZE: u8 = 4;

        for y in qr.lines_range(text_type, BORDER_SIZE) {
            info!(
                "{}",
                qr.line_as_str(text_type, BORDER_SIZE, false, false, y, tmp_buf)?
                    .0
            );
        }

        Ok(())
    }

    /// Return the standard QR code payload
    ///
    /// The returned QR code payload corresponds to the standard commissioning flow (i.e. `CommFlowType::Standard`)
    /// and contains no optional data.
    ///
    /// # Arguments
    /// - `disc_caps`: The discovery capabilities to be used in the QR code payload
    fn standard_qr_payload(
        &self,
        disc_caps: DiscoveryCapabilities,
    ) -> Result<QrPayload<'_, NoOptionalData>, Error> {
        let payload = QrPayload::new_from_basic_info(
            disc_caps,
            CommFlowType::Standard,
            self.dev_comm.clone(),
            self.dev_det,
            no_optional_data as _,
        );

        Ok(payload)
    }

    /// Return `true` if there is at least one commissioned fabric
    //
    // TODO:
    // The implementation of this method needs to change in future,
    // because the current implementation does not really track whether
    // `CommissioningComplete` had been actually received for the fabric.
    //
    // The fabric is created once we receive `AddNoc`, but that's just
    // not enough. The fabric should NOT be considered commissioned until
    // after we receive `CommissioningComplete` on behalf of a Case session
    // for the fabric in question.
    pub fn is_commissioned(&self) -> bool {
        self.with_state(|state| state.fabrics.iter().count() > 0)
    }

    /// Open a basic commissioning window
    ///
    /// The method will return an error if the commissioning window cannot be opened
    /// (due to another window already being opened, for example).
    ///
    /// # Arguments
    /// - `timeout_secs`: The timeout in seconds for the basic commissioning window
    pub fn open_basic_comm_window<C: Crypto>(
        &self,
        timeout_secs: u16,
        crypto: C,
        notify: &dyn ChangeNotify,
    ) -> Result<(), Error> {
        let notify_mdns = || self.notify_mdns();
        let notify_change =
            |endpt_id, clust_id, attr_id| notify.notify(endpt_id, clust_id, attr_id);

        self.with_state(|state| {
            let mut rand = crypto.rand()?;

            let mdns_id = rand.next_u64();

            let mut salt = SPAKE2P_VERIFIER_SALT_ZEROED;
            rand.fill_bytes(salt.access_mut());

            state.pase.open_basic_comm_window(
                mdns_id,
                salt.reference(),
                self.dev_comm.password.reference(),
                self.dev_comm.discriminator,
                timeout_secs,
                None,
                notify_mdns,
                notify_change,
            )
        })
    }

    /// Close the basic commissioning window
    ///
    /// The method will return Ok(false) if there is no active PASE commissioning window to close.
    pub fn close_comm_window(&self, notify: &dyn ChangeNotify) -> Result<bool, Error> {
        let notify_mdns = || self.notify_mdns();
        let notify_change =
            |endpt_id, clust_id, attr_id| notify.notify(endpt_id, clust_id, attr_id);

        self.with_state(|state| state.pase.close_comm_window(notify_mdns, notify_change))
    }

    /// Create a new transport runner instance
    pub fn transport_runner<C: Crypto>(&self, crypto: C) -> TransportRunner<'_, C> {
        TransportRunner::new(self, crypto)
    }

    /// Run the Matter transport layer.
    ///
    /// # Arguments
    /// - `crypto`: The crypto backend
    /// - `send`: The network send interface
    /// - `recv`: The network receive interface
    /// - `multicast`: The multicast network interface (for receiving groupcast messages)
    ///   When running on top of non-IP networks like BLE pass a no-op implementation like `NoNetwork` here and the multicast functionality will be disabled.
    pub async fn run<C, S, R, M>(
        &self,
        crypto: C,
        send: S,
        recv: R,
        multicast: M,
    ) -> Result<(), Error>
    where
        C: Crypto,
        S: NetworkSend,
        R: NetworkReceive,
        M: NetworkMulticast,
    {
        let mut transport_runner = self.transport_runner(crypto);

        transport_runner.run(send, recv, multicast).await
    }

    /// Access the Matter state by invoking a closure with a mutable reference to the state.
    pub fn with_state<F, R>(&self, f: F) -> R
    where
        F: FnOnce(&mut MatterState) -> R,
    {
        self.state.lock(|state| {
            let mut state = state.borrow_mut();
            f(&mut state)
        })
    }

    /// Reset the transport layer by clearing all sessions, exchanges, the RX buffer and the TX buffer
    /// NOTE: User should be careful _not_ to call this method while the transport layer and/or the built-in mDNS is running.
    pub fn reset_transport(&self) -> Result<(), Error> {
        self.with_state(|state| {
            state.sessions.reset();

            self.transport.reset()
        })
    }

    /// Notify that groups have changed (keys, key maps, or membership) and
    /// multicast registrations need updating.
    pub fn notify_groups_changed(&self) {
        self.groups_modified.notify();
    }

    /// Reset the Matter persistable state by removing all fabrics and resetting basic info settings
    ///
    /// Arguments:
    /// - `kv`: The key-value store to load the fabrics and basic info settings from
    /// - `buf`: A buffer to use for loading the fabrics and basic info settings
    pub async fn reset_persist<S: KvBlobStore>(
        &mut self,
        mut kv: S,
        buf: &mut [u8],
    ) -> Result<(), Error> {
        {
            let state = self.state.get_mut();
            let mut state = state.borrow_mut();

            state.fabrics.reset_persist(&mut kv, buf).await?;
            state
                .basic_info_settings
                .reset_persist(&mut kv, buf)
                .await?;
        }

        self.notify_mdns();

        Ok(())
    }

    /// Load fabrics from the given data
    ///
    /// Arguments:
    /// - `kv`: The key-value store to load the fabrics and basic info settings from
    /// - `buf`: A buffer to use for loading the fabrics and basic info settings
    pub async fn load_persist<S: KvBlobStore>(
        &mut self,
        mut kv: S,
        buf: &mut [u8],
    ) -> Result<(), Error> {
        {
            let state = self.state.get_mut();
            let mut state = state.borrow_mut();

            state.fabrics.load_persist(&mut kv, buf).await?;
            state.basic_info_settings.load_persist(&mut kv, buf).await?;
        }

        self.notify_mdns();

        Ok(())
    }

    /// Invoke the given closure for each currently published Matter mDNS service.
    pub fn mdns_services<C, F>(&self, notify_change: C, mut f: F) -> Result<(), Error>
    where
        C: FnMut(EndptId, ClusterId, AttrId),
        F: FnMut(MatterMdnsService) -> Result<(), Error>,
    {
        debug!("=== Currently published mDNS services");

        let notify_mdns = || self.notify_mdns();

        self.with_state(|state| {
            if let Some(comm_window) = state.pase.comm_window(notify_mdns, notify_change)? {
                // Do not remove this logging line or change its formatting.
                // C++ E2E tests rely on this log line to determine when the mDNS service is published
                debug!("mDNS service published: {:?}", comm_window.mdns_service());

                f(comm_window.mdns_service())?;
            }

            for fabric in state.fabrics.iter() {
                if let Some(service) = fabric.mdns_service() {
                    // Do not remove this logging line or change its formatting.
                    // C++ E2E tests rely on this log line to determine when the mDNS service is published
                    debug!("mDNS service published: {:?}", service);

                    f(service)?;
                }
            }

            debug!("===");

            Ok(())
        })
    }

    /// Notify that the Matter mDNS services _might_ have changed.
    pub(crate) fn notify_mdns(&self) {
        self.mdns_changed.notify();
    }

    /// A hook for user code to wait for notification that the Matter mDNS services might have changed.
    ///
    /// Once this future resolves, user code is supposed to inspect the mDNS services for changes, and
    /// if there are changes, re-publish the changed mDNS services in an mDNS responder accordingly.
    pub fn wait_mdns(&self) -> impl Future<Output = ()> + '_ {
        self.mdns_changed.wait()
    }
}

/// The internal state of the Matter Object
///
/// Public for unit tests.
pub struct MatterState {
    /// All fabrics
    ///
    /// Public for unit tests
    pub fabrics: Fabrics,
    /// All sessions
    sessions: Sessions,
    /// The PASE session state
    pase: Pase,
    /// The Failsafe state
    failsafe: FailSafe,
    /// The mutable basic information settings
    basic_info_settings: BasicInfoSettings,
}

impl MatterState {
    /// Create a new instance of MatterState
    #[inline(always)]
    const fn new(epoch: Epoch) -> Self {
        Self {
            fabrics: Fabrics::new(),
            sessions: Sessions::new(epoch),
            pase: Pase::new(epoch),
            failsafe: FailSafe::new(epoch),
            basic_info_settings: BasicInfoSettings::new(),
        }
    }

    /// Return an in-place initializer for MatterState
    fn init(epoch: Epoch) -> impl Init<Self> {
        init!(Self {
            fabrics <- Fabrics::init(),
            sessions <- Sessions::init(epoch),
            pase <- Pase::init(epoch),
            failsafe <- FailSafe::init(epoch),
            basic_info_settings <- BasicInfoSettings::init(),
        })
    }
}

#[cfg(test)]
pub mod test {
    use crate::{utils::epoch::dummy_epoch, Matter};

    pub fn test_matter() -> Matter<'static> {
        Matter::new(
            &crate::dm::devices::test::TEST_DEV_DET,
            crate::dm::devices::test::TEST_DEV_COMM,
            &crate::dm::devices::test::TEST_DEV_ATT,
            dummy_epoch,
            0,
        )
    }
}
