/*
 *
 *    Copyright (c) 2020-2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//! Core IDL parsing and code generation library for rs-matter.
//!
//! This crate contains the Matter IDL parser and Rust code generator,
//! extracted from the proc-macro crate so it can be used from both
//! proc macros and build.rs scripts.

// FIXME: With rust 1.92 the compiler emits an unused assignment lint, because
//        of the code generated by miette-derive. See https://github.com/zkat/miette/issues/458
#[allow(unused_assignments)]
mod idl;

pub use idl::{
    cluster, globals, Idl, IdlGenerateContext, CSA_STANDARD_CLUSTERS_IDL_V1_0_0_2,
    CSA_STANDARD_CLUSTERS_IDL_V1_1_0_2, CSA_STANDARD_CLUSTERS_IDL_V1_2_0_1,
    CSA_STANDARD_CLUSTERS_IDL_V1_3_0_0, CSA_STANDARD_CLUSTERS_IDL_V1_4_0_0,
    CSA_STANDARD_CLUSTERS_IDL_V1_4_2_0,
};
