/*
 *
 *    Copyright (c) 2026 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//! Core IDL parsing and code generation library for rs-matter.
//!
//! This crate contains the Matter IDL parser and Rust code generator,
//! extracted from the proc-macro crate so it can be used from build.rs scripts.

use std::path::Path;

use idl::{cluster_content, globals, Idl, IdlGenerateContext, CSA_STANDARD_CLUSTERS_IDL_V1_6_0_0};

// FIXME: With rust 1.92 the compiler emits an unused assignment lint, because
//        of the code generated by miette-derive. See https://github.com/zkat/miette/issues/458
#[allow(unused_assignments)]
mod idl;

/// Render a generated token stream as Rust source.
///
/// By default this uses a fast printer that only respects token spacing and
/// adds line breaks and indentation around blocks and statements. It is
/// several times faster than re-parsing the stream with `syn` and
/// pretty-printing it with `prettyplease`, which matters because the
/// generated code is ~30MB and the build script runs unoptimized in most
/// downstream builds.
///
/// Set `RS_MATTER_CODEGEN_PRETTY=1` to get fully formatted output instead,
/// e.g. when reading or diffing the generated code.
fn format_tokens(tokens: proc_macro2::TokenStream) -> String {
    if std::env::var_os("RS_MATTER_CODEGEN_PRETTY").is_some_and(|v| v == "1") {
        let file = syn::parse2(tokens).expect("Generated code is not valid Rust");
        return prettyplease::unparse(&file);
    }

    let mut out = String::new();
    print_tokens(tokens, &mut out, 0, true);
    out
}

/// Print `tokens` into `out`, one statement or item per line, indenting
/// the contents of `{}` groups by one level.
///
/// `in_block` is true when the tokens are direct children of a `{}` group
/// (or of the file), so that a `;` ends a line there but not inside `()`
/// or `[]` (e.g. `[u8; 4]`).
fn print_tokens(tokens: proc_macro2::TokenStream, out: &mut String, indent: usize, in_block: bool) {
    use proc_macro2::{Delimiter, Spacing, TokenTree};

    fn pad(out: &mut String, indent: usize) {
        for _ in 0..indent {
            out.push_str("    ");
        }
    }

    for tt in tokens {
        match tt {
            TokenTree::Group(g) => match g.delimiter() {
                Delimiter::Brace => {
                    out.push_str("{\n");
                    pad(out, indent + 1);
                    print_tokens(g.stream(), out, indent + 1, true);
                    out.push('\n');
                    pad(out, indent);
                    out.push_str("}\n");
                    pad(out, indent);
                }
                Delimiter::Parenthesis => {
                    out.push('(');
                    print_tokens(g.stream(), out, indent, false);
                    out.push_str(") ");
                }
                Delimiter::Bracket => {
                    out.push('[');
                    print_tokens(g.stream(), out, indent, false);
                    out.push_str("] ");
                }
                Delimiter::None => {
                    print_tokens(g.stream(), out, indent, in_block);
                }
            },
            TokenTree::Punct(p) => {
                let ch = p.as_char();
                out.push(ch);
                if ch == ';' && in_block {
                    out.push('\n');
                    pad(out, indent);
                } else if p.spacing() == Spacing::Alone {
                    // A `Joint` punct is immediately followed by the next
                    // token (`::`, `->`, `'a`, ...); a space would split it.
                    out.push(' ');
                }
            }
            TokenTree::Ident(_) | TokenTree::Literal(_) => {
                out.push_str(&tt.to_string());
                out.push(' ');
            }
        }
    }
}

/// Generate Rust code for all Matter clusters from the latest IDL specification.
///
/// Produces a multi-file output:
/// - `dest_dir/clusters_generated.rs` — root module with globals and `pub mod` declarations
/// - `dest_dir/clusters_generated/*.rs` — one file per cluster
///
/// The `rs_matter_crate` parameter controls how the generated code refers to
/// the rs-matter crate (e.g. `"crate"` when called from rs-matter's own build.rs,
/// or `"rs_matter"` when used by external crates).
pub fn generate(rs_matter_crate: &str, dest_dir: &Path) {
    let idl_file = CSA_STANDARD_CLUSTERS_IDL_V1_6_0_0;

    let idl = match Idl::parse(idl_file.into()) {
        Ok(result) => result,
        Err(e) => {
            let span_bytes = &idl_file.as_bytes()[e.error_location.offset()..];
            panic!(
                "Parser failed with {:?}, at\n===\n{}\n===\n",
                e,
                String::from_utf8_lossy(&span_bytes[..span_bytes.len().min(256)])
            );
        }
    };

    let context = IdlGenerateContext::new(rs_matter_crate);

    // Create the clusters_generated/ directory
    let clusters_dir = dest_dir.join("clusters_generated");
    std::fs::create_dir_all(&clusters_dir).unwrap();

    // Generate globals
    let globals_code = globals(&idl.globals, &context);

    // Generate each cluster as a separate file
    let mut cluster_files = Vec::new();

    for c in &idl.clusters {
        let (module_name, content) = cluster_content(c, &idl.globals, &context);

        let formatted = format_tokens(content);
        let file_path = clusters_dir.join(format!("{module_name}.rs"));
        std::fs::write(&file_path, formatted).unwrap();

        cluster_files.push((module_name, file_path.to_string_lossy().to_string()));
    }

    // Generate root module: globals + per-cluster mod declarations with #[path] attributes
    let globals_formatted = format_tokens(globals_code);

    let mut root = String::from("// IDL-generated code (via build.rs):\n\n");
    root.push_str(&globals_formatted);
    root.push('\n');

    for (module_name, _file_path) in &cluster_files {
        root.push_str(&format!(
            "/// Generated cluster module\n\
             #[allow(async_fn_in_trait)]\n\
             #[allow(unknown_lints)]\n\
             #[allow(clippy::uninlined_format_args)]\n\
             #[allow(unexpected_cfgs)]\n\
             pub mod {} {{\n\
                 include!(concat!(env!(\"OUT_DIR\"), \"/clusters_generated/{}.rs\"));\n\
             }}\n\n",
            module_name, module_name
        ));
    }

    std::fs::write(dest_dir.join("clusters_generated.rs"), root).unwrap();
}
