/*
 *
 *    Copyright (c) 2025-2026 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//! This module contains the base traits for the TLV builder framework, as well
//! as implementations of those traits for several built-in TLV types, like arrays,
//! octet strings, Utf8 strings, nullable and optional types.
//!
//! Note that putting aside those base builders, all other builders are expected to be
//! auto-generated by using the `idl_import` macro, rather than being typed by hand,
//! which is possible but very vberbose.
//!
//! The following is just an example of a builder for a struct TLV type `Foo` that has three fields:
//! ```ignore
//! pub struct FooBuilder<P, const F: usize> {
//!     p: P,
//! }
//!
//! impl<P> FooBuilder<P, 0>
//! where
//!     P: TLVBuilderParent,
//! {
//!     pub fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
//!         p.writer().start_struct(tag)?;
//!
//!         Ok(Self { p })
//!     }
//!
//!     pub fn field1(mut self, value: i32) -> Result<FooBuilder<P, 1>, Error> {
//!         self.p.writer().i32(&TLVTag::Context(0), value)?;
//!
//!         Ok(FooBuilder {
//!             p: self.p,
//!         })
//!     }
//! }
//!
//! impl<P> FooBuilder<P, 1>
//! where
//!     P: TLVBuilderParent,
//! {
//!     pub fn field2(mut self, value: u8) -> Result<FooBuilder<P, 2>, Error> {
//!         value.to_tlv(&TLVTag::Context(1), self.p.writer())?;
//!
//!         Ok(FooBuilder {
//!             p: self.p,
//!         })
//!     }
//! }
//!
//! impl<P> FooBuilder<P, 2>
//! where
//!     P: TLVBuilderParent,
//! {
//!     pub fn field3(self) -> Result<BarBuilder<FooBuilder<P, 3>, 0>, Error> {
//!         BarBuilder::new(FooBuilder { p: self.p }, &TLVTag::Context(2))
//!     }
//! }
//!
//! impl<P> FooBuilder<P, 3>
//! where
//!     P: TLVBuilderParent,
//! {
//!     pub fn finish(mut self) -> Result<P, Error> {
//!         self.p.writer().end_container()?;
//!
//!         Ok(self.p)
//!     }
//! }
//!
//! impl<P, const F: usize> TLVBuilderParent for FooBuilder<P, F>
//! where
//!     P: TLVBuilderParent,
//! {
//!     type Write = P::Write;
//!
//!     fn writer(&mut self) -> &mut Self::Write {
//!         self.p.writer()
//!     }
//!
//!     fn into_writer(self) -> Self::Write {
//!         self.p.into_writer()
//!     }
//! }
//!
//! impl<P> TLVBuilder<P> for FooBuilder<P, 0>
//! where
//!     P: TLVBuilderParent,
//! {
//!     fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
//!         Self::new(parent, tag)
//!     }
//! }
//!
//! pub struct FooArrayBuilder<P> {
//!     p: P,
//! }
//!
//! impl<P> FooArrayBuilder<P>
//! where
//!     P: TLVBuilderParent,
//! {
//!     pub fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
//!         p.writer().start_array(&tag)?;
//!
//!         Ok(Self { p })
//!     }
//!
//!     pub fn push(self) -> Result<FooBuilder<Self, 0>, Error> {
//!         FooBuilder::new(self, &TLVTag::Anonymous)
//!     }
//!
//!     pub fn end(mut self) -> Result<P, Error> {
//!         self.p.writer().end_container()?;
//!
//!         Ok(self.p)
//!     }
//! }
//!
//! impl<P> TLVBuilderParent for FooArrayBuilder<P>
//! where
//!     P: TLVBuilderParent,
//! {
//!     type Write = P::Write;
//!
//!     fn writer(&mut self) -> &mut Self::Write {
//!         self.p.writer()
//!     }
//!
//!     fn into_writer(self) -> Self::Write {
//!         self.p.into_writer()
//!     }
//! }
//!
//! impl<P> TLVBuilder<P> for FooArrayBuilder<P>
//! where
//!     P: TLVBuilderParent,
//! {
//!     fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
//!         Self::new(parent, tag)
//!     }
//! }
//!
//! pub struct BarBuilder<P, const F: usize> {
//!     p: P,
//! }
//!
//! impl<P> BarBuilder<P, 0>
//! where
//!     P: TLVBuilderParent,
//! {
//!     pub fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
//!         p.writer().start_struct(tag)?;
//!
//!         Ok(Self { p })
//!     }
//!
//!     pub fn field1(mut self, value: i32) -> Result<BarBuilder<P, 1>, Error> {
//!         self.p.writer().i32(&TLVTag::Context(0), value)?;
//!
//!         Ok(BarBuilder {
//!             p: self.p,
//!         })
//!     }
//! }
//!
//! impl<P> BarBuilder<P, 1>
//! where
//!     P: TLVBuilderParent,
//! {
//!     pub fn finish(mut self) -> Result<P, Error> {
//!         self.p.writer().end_container()?;
//!
//!         Ok(self.p)
//!     }
//! }
//!
//! impl<P, const F: usize> TLVBuilderParent for BarBuilder<P, F>
//! where
//!     P: TLVBuilderParent,
//! {
//!     type Write = P::Write;
//!
//!     fn writer(&mut self) -> &mut Self::Write {
//!         self.p.writer()
//!     }
//!
//!     fn into_writer(self) -> Self::Write {
//!         self.p.into_writer()
//!     }
//! }
//!
//! impl<P> TLVBuilder<P> for BarBuilder<P, 0>
//! where
//!     P: TLVBuilderParent,
//! {
//!     fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
//!         Self::new(parent, tag)
//!     }
//! }
//!```

use core::marker::PhantomData;

use crate::error::Error;
use crate::tlv::{TLVTag, TLVWrite};

use super::{Nullable, Octets, ToTLV, Utf8Str};

/// The `TLVBuilder` trait is used to implement a TLV builder for a certain TLV type.
///
/// A TLV builder is a helper struct that allows for an ergonomic writing of its
/// corresponding TLV type into a `TLVWrite` trait implementation.
///
/// The TLV builders' implementation is zero-cost, in that it is completely erased to
/// raw TLV writes on the wrapped `TLVWrite` trait type by the compiler.
pub trait TLVBuilder<P>: Sized
where
    P: TLVBuilderParent,
{
    /// Create a new TLV builder for the given parent and tag.
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error>;

    /// Call a closure with the builder and return the result.
    fn with<F>(self, f: F) -> Result<P, Error>
    where
        F: FnOnce(Self) -> Result<P, Error>,
    {
        f(self)
    }

    /// Convert itself into a writer.
    ///
    /// Should be used when the user prefers to use the raw `TLVWrite`
    /// interface to write the TLV type.
    ///
    /// NOTE:
    /// Use this method with caution, as it will consume the builder!
    /// You are then on your own so as to write - using the parent's writer - the correct TLV data
    /// that is otherwise performed by the builder.
    fn unchecked_into_parent(self) -> P;
}

/// Each `TLVBuilder<P>` trait implementation has a parent - `P`
/// which should implement the `TLVBuilderParent` trait.
///
/// The `TLVBuilderParent` trait is used to provide a way for the
/// `TLVBuilder` to access the wrapped `TLVWrite` trait, as well as to model
/// the nesting of the TLV builders, for complex TLV types like structs-of-structs,
/// or arrays-of-structs and so on.
///
/// Also - by convention - once a `TLVBuilder` implementation has finished (ended),
/// it should return its parent type `P`. This provides for extra ertgonomics when
/// using the builder, as the user cannot "forget" to build the complete TLV type which
/// is expected.
#[cfg(not(feature = "defmt"))]
pub trait TLVBuilderParent: Sized + core::fmt::Debug {
    /// The type of the writer.
    type Write: TLVWrite;

    /// Return a mutable reference to the writer.
    fn writer(&mut self) -> &mut Self::Write;
}

#[cfg(feature = "defmt")]
pub trait TLVBuilderParent: Sized + core::fmt::Debug + defmt::Format {
    /// The type of the writer.
    type Write: TLVWrite;

    /// Return a mutable reference to the writer.
    fn writer(&mut self) -> &mut Self::Write;
}

/// A root-level TLV builder parent, that wraps a `TLVWrite` implementation.
pub struct TLVWriteParent<S, W>(S, W);

impl<S, W> TLVWriteParent<S, W> {
    /// Create a new `TLVWriteParent` for the given writer.
    pub const fn new(id: S, writer: W) -> Self {
        Self(id, writer)
    }
}

impl<S, W> core::fmt::Debug for TLVWriteParent<S, W>
where
    S: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self.0)
    }
}

#[cfg(feature = "defmt")]
impl<S, W> defmt::Format for TLVWriteParent<S, W>
where
    S: core::fmt::Debug + defmt::Format,
{
    fn format(&self, fmt: defmt::Formatter) {
        defmt::write!(fmt, "{:?}", self.0);
    }
}

#[cfg(not(feature = "defmt"))]
impl<S, W> TLVBuilderParent for TLVWriteParent<S, W>
where
    S: core::fmt::Debug,
    W: TLVWrite,
{
    type Write = W;

    fn writer(&mut self) -> &mut Self::Write {
        &mut self.1
    }
}

#[cfg(feature = "defmt")]
impl<S, W> TLVBuilderParent for TLVWriteParent<S, W>
where
    S: core::fmt::Debug + defmt::Format,
    W: TLVWrite,
{
    type Write = W;

    fn writer(&mut self) -> &mut Self::Write {
        &mut self.1
    }
}

/// The `ToTLVBuilder` is a helper struct that allows for an ergonomic writing of
/// a TLV type that implements the `ToTLV` trait into a `TLVWrite` implementation.
///
/// This implementation is useful when the `T` type implements `ToTLV`.
///
/// Note that this implementation should be avoided when `T` has a large size, as it
/// needs the `T` instance to be materialized prior to writing into the TLV.
pub struct ToTLVBuilder<P, T> {
    parent: P,
    tag: TLVTag,
    _t: PhantomData<fn() -> T>,
}

impl<P, T> ToTLVBuilder<P, T>
where
    P: TLVBuilderParent,
    T: ToTLV + 'static,
{
    /// Create a new `ToTLVBuilder` for the given parent.
    pub fn new(parent: P, tag: &TLVTag) -> Self {
        Self {
            parent,
            tag: tag.clone(),
            _t: PhantomData,
        }
    }

    /// Write the TLV type into the writer.
    #[cfg(not(feature = "defmt"))]
    pub fn set(mut self, tlv: &T) -> Result<P, Error>
    where
        T: core::fmt::Debug,
    {
        #[cfg(feature = "log")]
        log::debug!("{:?}::TLV -> {:?} +", self, tlv);

        tlv.to_tlv(&self.tag, self.parent.writer())?;

        Ok(self.parent)
    }

    #[cfg(feature = "defmt")]
    pub fn set(mut self, tlv: &T) -> Result<P, Error>
    where
        T: core::fmt::Debug + defmt::Format,
    {
        defmt::debug!("{:?}::TLV[] -> {:?} +", self, tlv);

        tlv.to_tlv(&self.tag, self.parent.writer())?;

        Ok(self.parent)
    }
}

impl<P, T> core::fmt::Debug for ToTLVBuilder<P, T>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P, T> defmt::Format for ToTLVBuilder<P, T>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}", self.parent)
    }
}

impl<P, T> TLVBuilderParent for ToTLVBuilder<P, T>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P, T> TLVBuilder<P> for ToTLVBuilder<P, T>
where
    P: TLVBuilderParent,
    T: ToTLV + 'static,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Ok(Self::new(parent, tag))
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

/// The `ToTLVArrayBuilder` is a helper struct that allows for an ergonomic writing of
/// a TLV array into a `TLVWrite` implementation.
///
/// This implementation is useful when the `T` elements of the array implement `ToTLV`.
///
/// Note that this implementation should be avoided when `T` has a large size, as it
/// needs the `T` instances to be materialized prior to writing into the array.
pub struct ToTLVArrayBuilder<P, T> {
    _t: PhantomData<fn() -> T>,
    parent: P,
}

impl<P, T> ToTLVArrayBuilder<P, T>
where
    P: TLVBuilderParent,
    T: ToTLV + 'static,
{
    /// Create a new TLV array builder for the given parent and tag.
    pub fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
        p.writer().start_array(tag)?;

        Ok(Self {
            parent: p,
            _t: PhantomData,
        })
    }

    /// Push a new element into the array.
    #[cfg(not(feature = "defmt"))]
    pub fn push(mut self, tlv: &T) -> Result<Self, Error>
    where
        T: core::fmt::Debug,
    {
        #[cfg(feature = "log")]
        log::debug!("{:?}::TLV[] -> {:?} +", self, tlv);

        tlv.to_tlv(&TLVTag::Anonymous, self.parent.writer())?;

        Ok(self)
    }

    #[cfg(feature = "defmt")]
    pub fn push(mut self, tlv: &T) -> Result<Self, Error>
    where
        T: core::fmt::Debug + defmt::Format,
    {
        defmt::debug!("{:?}::TLV[] -> {:?} +", self, tlv);

        tlv.to_tlv(&TLVTag::Anonymous, self.parent.writer())?;

        Ok(self)
    }

    /// Finish the array and return the parent.
    pub fn end(mut self) -> Result<P, Error> {
        self.parent.writer().end_container()?;

        Ok(self.parent)
    }
}

impl<P, T> core::fmt::Debug for ToTLVArrayBuilder<P, T>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}[]", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P, T> defmt::Format for ToTLVArrayBuilder<P, T>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}[]", self.parent)
    }
}

impl<P, T> TLVBuilderParent for ToTLVArrayBuilder<P, T>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P, T> TLVBuilder<P> for ToTLVArrayBuilder<P, T>
where
    P: TLVBuilderParent,
    T: ToTLV + 'static,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Self::new(parent, tag)
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

/// A TLV builder for returning a Utf8 string value.
pub struct Utf8StrBuilder<P> {
    parent: P,
    tag: TLVTag,
}

impl<P> Utf8StrBuilder<P>
where
    P: TLVBuilderParent,
{
    /// Create a new `Utf8StrBuilder` for the given parent.
    pub fn new(parent: P, tag: &TLVTag) -> Self {
        Self {
            parent,
            tag: tag.clone(),
        }
    }

    /// Write the Utf8 string type into the writer.
    pub fn set(mut self, tlv: Utf8Str<'_>) -> Result<P, Error> {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::Utf8 -> {:?} +", self, tlv);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::Utf8 -> {:?} +", self, tlv);

        tlv.to_tlv(&self.tag, self.parent.writer())?;

        Ok(self.parent)
    }
}

impl<P> core::fmt::Debug for Utf8StrBuilder<P>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P> defmt::Format for Utf8StrBuilder<P>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}", self.parent)
    }
}

impl<P> TLVBuilderParent for Utf8StrBuilder<P>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P> TLVBuilder<P> for Utf8StrBuilder<P>
where
    P: TLVBuilderParent,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Ok(Self::new(parent, tag))
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

/// The `Utf8StrArrayBuilder` is a helper struct that allows for an ergonomic writing of
/// a TLV array containing Utf8 strings into a `TLVWrite` implementation.
pub struct Utf8StrArrayBuilder<P> {
    parent: P,
}

impl<P> Utf8StrArrayBuilder<P>
where
    P: TLVBuilderParent,
{
    /// Create a new TLV Utf8 array builder for the given parent and tag.
    pub fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
        p.writer().start_array(tag)?;

        Ok(Self { parent: p })
    }

    /// Push a new Utf8 string into the array.
    pub fn push(mut self, tlv: Utf8Str<'_>) -> Result<Self, Error> {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::Utf8[] -> {:?} +", self, tlv);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::Utf8[] -> {:?} +", self, tlv);

        tlv.to_tlv(&TLVTag::Anonymous, self.parent.writer())?;

        Ok(self)
    }

    /// Finish the array and return the parent.
    pub fn end(mut self) -> Result<P, Error> {
        self.parent.writer().end_container()?;

        Ok(self.parent)
    }
}

impl<P> core::fmt::Debug for Utf8StrArrayBuilder<P>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}[]", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P> defmt::Format for Utf8StrArrayBuilder<P>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}[]", self.parent)
    }
}

impl<P> TLVBuilderParent for Utf8StrArrayBuilder<P>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P> TLVBuilder<P> for Utf8StrArrayBuilder<P>
where
    P: TLVBuilderParent,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Self::new(parent, tag)
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

/// A TLV builder for returning an octet string value.
pub struct OctetsBuilder<P> {
    parent: P,
    tag: TLVTag,
}

impl<P> OctetsBuilder<P>
where
    P: TLVBuilderParent,
{
    /// Create a new `OctetsBuilder` for the given parent.
    pub fn new(parent: P, tag: &TLVTag) -> Self {
        Self {
            parent,
            tag: tag.clone(),
        }
    }

    /// Write the TLV type into the writer.
    pub fn set(mut self, tlv: Octets<'_>) -> Result<P, Error> {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::Octets -> {:?} +", self, tlv);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::Octets -> {:?} +", self, tlv);

        tlv.to_tlv(&self.tag, self.parent.writer())?;

        Ok(self.parent)
    }
}

impl<P> core::fmt::Debug for OctetsBuilder<P>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P> defmt::Format for OctetsBuilder<P>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}", self.parent)
    }
}

impl<P> TLVBuilderParent for OctetsBuilder<P>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P> TLVBuilder<P> for OctetsBuilder<P>
where
    P: TLVBuilderParent,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Ok(Self::new(parent, tag))
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

/// The `OctetsArrayBuilder` is a helper struct that allows for an ergonomic writing of
/// a TLV array of octet strings into a `TLVWrite` implementation.
pub struct OctetsArrayBuilder<P> {
    parent: P,
}

impl<P> OctetsArrayBuilder<P>
where
    P: TLVBuilderParent,
{
    /// Create a new octets TLV array builder for the given parent and tag.
    pub fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
        p.writer().start_array(tag)?;

        Ok(Self { parent: p })
    }

    /// Push a new octet string into the array.
    pub fn push(mut self, tlv: Octets<'_>) -> Result<Self, Error> {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::Octets[] -> {:?} +", self, tlv);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::Octets[] -> {:?} +", self, tlv);

        tlv.to_tlv(&TLVTag::Anonymous, self.parent.writer())?;

        Ok(self)
    }

    /// Finish the array and return the parent.
    pub fn end(mut self) -> Result<P, Error> {
        self.parent.writer().end_container()?;

        Ok(self.parent)
    }
}

impl<P> core::fmt::Debug for OctetsArrayBuilder<P>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}[]", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P> defmt::Format for OctetsArrayBuilder<P>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}[]", self.parent)
    }
}

impl<P> TLVBuilderParent for OctetsArrayBuilder<P>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P> TLVBuilder<P> for OctetsArrayBuilder<P>
where
    P: TLVBuilderParent,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Self::new(parent, tag)
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

/// A builder for a nullable TLV type.
pub struct NullableBuilder<P, T> {
    parent: P,
    tag: TLVTag,
    _t: PhantomData<fn() -> T>,
}

impl<P, T> NullableBuilder<P, T>
where
    P: TLVBuilderParent,
    T: TLVBuilder<P>,
{
    /// Create a new nullable TLV builder for the given parent and tag.
    pub fn new(parent: P, tag: &TLVTag) -> Self {
        Self {
            parent,
            tag: tag.clone(),
            _t: PhantomData,
        }
    }

    /// Write a null value into the TLV and return the parent.
    pub fn null(mut self) -> Result<P, Error> {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::nullable -> null +", self);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::nullable -> null +", self);

        self.parent.writer().null(&self.tag)?;

        Ok(self.parent)
    }

    /// Create and return the builder for the non-null value.
    pub fn non_null(self) -> Result<T, Error> {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::nullable -> (not_null) +", self);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::nullable -> (not_null) +", self);

        T::new(self.parent, &self.tag)
    }

    /// If `condition` is `true`, call the closure with the non-null builder.
    /// If `condition` is `false`, write null and return the parent.
    pub fn with_non_null_if<F>(self, condition: bool, f: F) -> Result<P, Error>
    where
        F: FnOnce(T) -> Result<P, Error>,
    {
        if condition {
            f(self.non_null()?)
        } else {
            self.null()
        }
    }

    /// If the input is non-null, call the closure with the non-null builder and the input.
    /// If the input is null, write null and return the parent.
    pub fn with_non_null<I, F>(self, input: Nullable<I>, f: F) -> Result<P, Error>
    where
        F: FnOnce(&I, T) -> Result<P, Error>,
    {
        if let Some(input) = input.as_opt_ref() {
            f(input, self.non_null()?)
        } else {
            self.null()
        }
    }
}

impl<P, T> core::fmt::Debug for NullableBuilder<P, T>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P, T> defmt::Format for NullableBuilder<P, T>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}", self.parent)
    }
}

impl<P, T> TLVBuilderParent for NullableBuilder<P, T>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P, T> TLVBuilder<P> for NullableBuilder<P, T>
where
    P: TLVBuilderParent,
    T: TLVBuilder<P>,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Ok(Self::new(parent, tag))
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

/// A builder for an optional TLV type.
pub struct OptionalBuilder<P, T> {
    parent: P,
    tag: TLVTag,
    _t: PhantomData<fn() -> T>,
}

impl<P, T> OptionalBuilder<P, T>
where
    P: TLVBuilderParent,
    T: TLVBuilder<P>,
{
    /// Create a new optional TLV builder for the given parent and tag.
    pub fn new(parent: P, tag: &TLVTag) -> Self {
        Self {
            parent,
            tag: tag.clone(),
            _t: PhantomData,
        }
    }

    /// Skip writing the TLV type and return the parent.
    pub fn none(self) -> P {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::optional -> none +", self);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::optional -> none +", self);

        self.parent
    }

    /// Create and return the builder for the non-optional value.
    pub fn some(self) -> Result<T, Error> {
        #[cfg(feature = "defmt")]
        defmt::debug!("{:?}::optional -> (some) +", self);
        #[cfg(feature = "log")]
        ::log::debug!("{:?}::optional -> (some) +", self);

        T::new(self.parent, &self.tag)
    }

    /// If `condition` is `true`, call the closure with the non-optional builder.
    /// If `condition` is `false`, return the parent.
    pub fn with_some_if<F>(self, condition: bool, f: F) -> Result<P, Error>
    where
        F: FnOnce(T) -> Result<P, Error>,
    {
        if condition {
            f(self.some()?)
        } else {
            Ok(self.none())
        }
    }

    /// If the input is `Some`, call the closure with the non-optional builder and the input.
    /// If the input is `None`, return the parent.
    pub fn with_some<I, F>(self, input: Option<I>, f: F) -> Result<P, Error>
    where
        F: FnOnce(&I, T) -> Result<P, Error>,
    {
        if let Some(input) = input.as_ref() {
            f(input, self.some()?)
        } else {
            Ok(self.none())
        }
    }
}

impl<P, T> core::fmt::Debug for OptionalBuilder<P, T>
where
    P: core::fmt::Debug,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self.parent)
    }
}

#[cfg(feature = "defmt")]
impl<P, T> defmt::Format for OptionalBuilder<P, T>
where
    P: defmt::Format,
{
    fn format(&self, f: defmt::Formatter<'_>) {
        defmt::write!(f, "{:?}", self.parent)
    }
}

impl<P, T> TLVBuilderParent for OptionalBuilder<P, T>
where
    P: TLVBuilderParent,
{
    type Write = P::Write;

    fn writer(&mut self) -> &mut Self::Write {
        self.parent.writer()
    }
}

impl<P, T> TLVBuilder<P> for OptionalBuilder<P, T>
where
    P: TLVBuilderParent,
    T: TLVBuilder<P>,
{
    fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
        Ok(Self::new(parent, tag))
    }

    fn unchecked_into_parent(self) -> P {
        self.parent
    }
}

#[cfg(test)]
mod tests {
    use crate::error::{Error, ErrorCode};
    use crate::tlv::{FromTLV, Nullable, Octets, TLVArray, TLVElement, TLVTag, TLVWrite};
    use crate::utils::storage::WriteBuf;

    use super::{
        NullableBuilder, OctetsArrayBuilder, OctetsBuilder, OptionalBuilder, TLVBuilder,
        TLVBuilderParent, TLVWriteParent, ToTLVArrayBuilder, ToTLVBuilder, Utf8StrArrayBuilder,
        Utf8StrBuilder,
    };

    /// The root parent used by every test: a `WriteBuf` wrapped in a `TLVWriteParent`
    /// whose Debug name is `"root"`.
    type Root<'a, 'b> = TLVWriteParent<&'static str, &'a mut WriteBuf<'b>>;

    fn root<'a, 'b>(wb: &'a mut WriteBuf<'b>) -> Root<'a, 'b> {
        TLVWriteParent::new("root", wb)
    }

    /// A hand-written struct builder in the shape the module docs describe:
    /// `{ 0: u8, 1: octets }`. Used to exercise nesting and parent hand-back.
    struct PairBuilder<P, const F: usize> {
        p: P,
    }

    impl<P: TLVBuilderParent> PairBuilder<P, 0> {
        fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
            p.writer().start_struct(tag)?;
            Ok(Self { p })
        }

        fn first(mut self, value: u8) -> Result<PairBuilder<P, 1>, Error> {
            self.p.writer().u8(&TLVTag::Context(0), value)?;
            Ok(PairBuilder { p: self.p })
        }
    }

    impl<P: TLVBuilderParent> PairBuilder<P, 1> {
        fn second(self) -> OctetsBuilder<PairBuilder<P, 2>> {
            OctetsBuilder::new(PairBuilder { p: self.p }, &TLVTag::Context(1))
        }
    }

    impl<P: TLVBuilderParent> PairBuilder<P, 2> {
        fn finish(mut self) -> Result<P, Error> {
            self.p.writer().end_container()?;
            Ok(self.p)
        }
    }

    impl<P: TLVBuilderParent, const F: usize> TLVBuilderParent for PairBuilder<P, F> {
        type Write = P::Write;

        fn writer(&mut self) -> &mut Self::Write {
            self.p.writer()
        }
    }

    impl<P: core::fmt::Debug, const F: usize> core::fmt::Debug for PairBuilder<P, F> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            write!(f, "{:?}::Pair<{}>", self.p, F)
        }
    }

    #[cfg(feature = "defmt")]
    impl<P: defmt::Format, const F: usize> defmt::Format for PairBuilder<P, F> {
        fn format(&self, f: defmt::Formatter<'_>) {
            defmt::write!(f, "{:?}::Pair<{}>", self.p, F)
        }
    }

    impl<P: TLVBuilderParent> TLVBuilder<P> for PairBuilder<P, 0> {
        fn new(parent: P, tag: &TLVTag) -> Result<Self, Error> {
            Self::new(parent, tag)
        }

        fn unchecked_into_parent(self) -> P {
            self.p
        }
    }

    /// Array-of-`Pair` builder, again in the shape of the module docs.
    struct PairArrayBuilder<P> {
        p: P,
    }

    impl<P: TLVBuilderParent> PairArrayBuilder<P> {
        fn new(mut p: P, tag: &TLVTag) -> Result<Self, Error> {
            p.writer().start_array(tag)?;
            Ok(Self { p })
        }

        fn push(self) -> Result<PairBuilder<Self, 0>, Error> {
            PairBuilder::new(self, &TLVTag::Anonymous)
        }

        fn end(mut self) -> Result<P, Error> {
            self.p.writer().end_container()?;
            Ok(self.p)
        }
    }

    impl<P: TLVBuilderParent> TLVBuilderParent for PairArrayBuilder<P> {
        type Write = P::Write;

        fn writer(&mut self) -> &mut Self::Write {
            self.p.writer()
        }
    }

    impl<P: core::fmt::Debug> core::fmt::Debug for PairArrayBuilder<P> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            write!(f, "{:?}[]", self.p)
        }
    }

    #[cfg(feature = "defmt")]
    impl<P: defmt::Format> defmt::Format for PairArrayBuilder<P> {
        fn format(&self, f: defmt::Formatter<'_>) {
            defmt::write!(f, "{:?}[]", self.p)
        }
    }

    /// The decoded counterpart of what `PairBuilder` writes.
    #[derive(FromTLV, Debug, PartialEq)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    #[tlvargs(lifetime = "'a")]
    struct Pair<'a> {
        first: u8,
        second: Octets<'a>,
    }

    #[test]
    fn to_tlv_builder_writes_value_with_tag() {
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        ToTLVBuilder::<_, u32>::new(root(&mut wb), &TLVTag::Context(5))
            .set(&7)
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x24, 5, 7]);

        wb.reset();
        ToTLVBuilder::<_, u32>::new(root(&mut wb), &TLVTag::Context(5))
            .set(&0x1234)
            .unwrap();

        let elem = TLVElement::new(wb.as_slice());
        assert_eq!(elem.tag().unwrap(), TLVTag::Context(5));
        assert_eq!(elem.u32().unwrap(), 0x1234);
    }

    #[test]
    fn to_tlv_array_builder_pushes_and_ends() {
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        ToTLVArrayBuilder::<_, u16>::new(root(&mut wb), &TLVTag::Context(1))
            .unwrap()
            .push(&1)
            .unwrap()
            .push(&0x1234)
            .unwrap()
            .end()
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x36, 1, 0x04, 1, 0x05, 0x34, 0x12, 0x18]);

        let arr = TLVArray::<u16>::new(TLVElement::new(wb.as_slice())).unwrap();
        assert!(arr.iter().map(Result::unwrap).eq([1, 0x1234]));

        wb.reset();
        ToTLVArrayBuilder::<_, u16>::new(root(&mut wb), &TLVTag::Anonymous)
            .unwrap()
            .end()
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x16, 0x18]);
    }

    #[test]
    fn utf8_builders_round_trip() {
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        Utf8StrBuilder::new(root(&mut wb), &TLVTag::Anonymous)
            .set("hi")
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x0C, 2, b'h', b'i']);
        assert_eq!(TLVElement::new(wb.as_slice()).utf8().unwrap(), "hi");

        wb.reset();
        Utf8StrArrayBuilder::new(root(&mut wb), &TLVTag::Anonymous)
            .unwrap()
            .push("a")
            .unwrap()
            .push("")
            .unwrap()
            .end()
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x16, 0x0C, 1, b'a', 0x0C, 0, 0x18]);

        let arr = TLVArray::<&str>::new(TLVElement::new(wb.as_slice())).unwrap();
        assert!(arr.iter().map(Result::unwrap).eq(["a", ""]));
    }

    #[test]
    fn octets_builders_round_trip() {
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        OctetsBuilder::new(root(&mut wb), &TLVTag::Context(3))
            .set(Octets(&[1, 2, 3]))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x30, 3, 3, 1, 2, 3]);

        wb.reset();
        OctetsArrayBuilder::new(root(&mut wb), &TLVTag::Anonymous)
            .unwrap()
            .push(Octets(&[9]))
            .unwrap()
            .push(Octets(&[]))
            .unwrap()
            .end()
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x16, 0x10, 1, 9, 0x10, 0, 0x18]);

        let arr = TLVArray::<Octets>::new(TLVElement::new(wb.as_slice())).unwrap();
        assert!(arr
            .iter()
            .map(Result::unwrap)
            .eq([Octets(&[9]), Octets(&[])]));
    }

    #[test]
    fn nullable_builder_writes_null_or_delegates() {
        type NullU8<'a, 'b> = NullableBuilder<Root<'a, 'b>, ToTLVBuilder<Root<'a, 'b>, u8>>;

        let tag = TLVTag::Context(2);
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        NullU8::new(root(&mut wb), &tag).null().unwrap();
        assert_eq!(wb.as_slice(), &[0x34, 2]);
        TLVElement::new(wb.as_slice()).null().unwrap();

        wb.reset();
        NullU8::new(root(&mut wb), &tag)
            .non_null()
            .unwrap()
            .set(&7)
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x24, 2, 7]);

        wb.reset();
        NullU8::new(root(&mut wb), &tag)
            .with_non_null(Nullable::some(9u8), |v, b| b.set(v))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x24, 2, 9]);

        wb.reset();
        NullU8::new(root(&mut wb), &tag)
            .with_non_null(Nullable::<u8>::none(), |v, b| b.set(v))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x34, 2]);

        wb.reset();
        NullU8::new(root(&mut wb), &tag)
            .with_non_null_if(true, |b| b.set(&1))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x24, 2, 1]);

        wb.reset();
        NullU8::new(root(&mut wb), &tag)
            .with_non_null_if(false, |b| b.set(&1))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x34, 2]);
    }

    #[test]
    fn optional_builder_skips_or_delegates() {
        type OptU8<'a, 'b> = OptionalBuilder<Root<'a, 'b>, ToTLVBuilder<Root<'a, 'b>, u8>>;

        let tag = TLVTag::Context(2);
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        OptU8::new(root(&mut wb), &tag).none();
        assert!(wb.as_slice().is_empty());

        OptU8::new(root(&mut wb), &tag)
            .some()
            .unwrap()
            .set(&7)
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x24, 2, 7]);

        wb.reset();
        OptU8::new(root(&mut wb), &tag)
            .with_some(Some(3u8), |v, b| b.set(v))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x24, 2, 3]);

        wb.reset();
        OptU8::new(root(&mut wb), &tag)
            .with_some(None::<u8>, |v, b| b.set(v))
            .unwrap();
        assert!(wb.as_slice().is_empty());

        OptU8::new(root(&mut wb), &tag)
            .with_some_if(true, |b| b.set(&1))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x24, 2, 1]);

        wb.reset();
        OptU8::new(root(&mut wb), &tag)
            .with_some_if(false, |b| b.set(&1))
            .unwrap();
        assert!(wb.as_slice().is_empty());
    }

    #[test]
    fn nested_struct_and_array_builders_hand_back_parent() {
        let mut buf = [0; 32];
        let mut wb = WriteBuf::new(&mut buf);

        // `end()` of the innermost builder returns the array builder, which in turn
        // returns the root once ended.
        let parent = PairArrayBuilder::new(root(&mut wb), &TLVTag::Anonymous)
            .unwrap()
            .push()
            .unwrap()
            .first(1)
            .unwrap()
            .second()
            .set(Octets(&[0xAA]))
            .unwrap()
            .finish()
            .unwrap()
            .push()
            .unwrap()
            .first(2)
            .unwrap()
            .second()
            .set(Octets(&[]))
            .unwrap()
            .finish()
            .unwrap()
            .end()
            .unwrap();
        assert_eq!(format!("{parent:?}"), "\"root\"");
        drop(parent);

        assert_eq!(
            wb.as_slice(),
            &[
                0x16, 0x15, 0x24, 0, 1, 0x30, 1, 1, 0xAA, 0x18, 0x15, 0x24, 0, 2, 0x30, 1, 0, 0x18,
                0x18
            ]
        );

        let arr = TLVArray::<Pair>::new(TLVElement::new(wb.as_slice())).unwrap();
        assert!(arr.iter().map(Result::unwrap).eq([
            Pair {
                first: 1,
                second: Octets(&[0xAA]),
            },
            Pair {
                first: 2,
                second: Octets(&[]),
            },
        ]));

        // A struct builder as the non-null / some branch of the wrapper builders
        wb.reset();
        NullableBuilder::<_, PairBuilder<Root, 0>>::new(root(&mut wb), &TLVTag::Context(7))
            .non_null()
            .unwrap()
            .first(5)
            .unwrap()
            .second()
            .set(Octets(b"x"))
            .unwrap()
            .finish()
            .unwrap();
        assert_eq!(
            wb.as_slice(),
            &[0x35, 7, 0x24, 0, 5, 0x30, 1, 1, b'x', 0x18]
        );
        assert_eq!(
            Pair::from_tlv(&TLVElement::new(wb.as_slice())).unwrap(),
            Pair {
                first: 5,
                second: Octets(b"x"),
            }
        );

        wb.reset();
        OptionalBuilder::<_, PairBuilder<Root, 0>>::new(root(&mut wb), &TLVTag::Context(7)).none();
        assert!(wb.as_slice().is_empty());
    }

    #[test]
    fn with_closure_and_unchecked_into_parent() {
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        ToTLVBuilder::<_, u8>::new(root(&mut wb), &TLVTag::Anonymous)
            .with(|b| b.set(&1))
            .unwrap();
        assert_eq!(wb.as_slice(), &[0x04, 1]);

        // `unchecked_into_parent` hands the parent back without closing the container;
        // the caller is then responsible for the raw writes.
        wb.reset();
        let mut parent = Utf8StrArrayBuilder::new(root(&mut wb), &TLVTag::Anonymous)
            .unwrap()
            .unchecked_into_parent();
        parent.writer().end_container().unwrap();
        drop(parent);
        assert_eq!(wb.as_slice(), &[0x16, 0x18]);
    }

    /// Writes a fixed nested value through the builders; used by the sizing test.
    fn write_sample(wb: &mut WriteBuf<'_>) -> Result<(), Error> {
        PairArrayBuilder::new(root(wb), &TLVTag::Anonymous)?
            .push()?
            .first(1)?
            .second()
            .set(Octets(&[1, 2, 3]))?
            .finish()?
            .end()?;

        Ok(())
    }

    #[test]
    fn exact_fit_succeeds_and_one_byte_short_fails() {
        let mut big = [0; 64];
        let mut wb = WriteBuf::new(&mut big);
        write_sample(&mut wb).unwrap();
        let len = wb.as_slice().len();
        let mut full = [0; 64];
        full[..len].copy_from_slice(wb.as_slice());
        let full = &full[..len];

        // Exactly big enough: everything fits, output is identical
        let mut exact = [0; 64];
        let mut wb = WriteBuf::new(&mut exact[..len]);
        write_sample(&mut wb).unwrap();
        assert_eq!(wb.as_slice(), full);

        // One byte short: the closing byte of the outer array cannot be written.
        // What was written before the failure is a strict prefix of the full output
        // and the tail can be rewound to the pre-build position.
        let mut short = [0; 64];
        let mut wb = WriteBuf::new(&mut short[..len - 1]);
        let tail = wb.get_tail();
        let err = write_sample(&mut wb).unwrap_err();
        assert_eq!(err.code(), ErrorCode::NoSpace);
        assert_eq!(wb.as_slice(), &full[..len - 1]);

        wb.rewind_to(tail);
        assert!(wb.as_slice().is_empty());
        wb.u8(&TLVTag::Anonymous, 1).unwrap();
        assert_eq!(wb.as_slice(), &[0x04, 1]);
    }

    #[test]
    fn tag_forms_are_preserved() {
        let tags = [
            TLVTag::Anonymous,
            TLVTag::Context(3),
            TLVTag::CommonPrf16(0x1234),
            TLVTag::CommonPrf32(0x1234_5678),
            TLVTag::ImplPrf16(1),
            TLVTag::ImplPrf32(2),
            TLVTag::FullQual48 {
                vendor_id: 0xFFF1,
                profile: 0xDEED,
                tag: 0xAA00,
            },
            TLVTag::FullQual64 {
                vendor_id: 0xFFF1,
                profile: 0xDEED,
                tag: 0xAA00_0001,
            },
        ];

        for tag in tags {
            let mut buf = [0; 16];
            let mut wb = WriteBuf::new(&mut buf);

            ToTLVBuilder::<_, u8>::new(root(&mut wb), &tag)
                .set(&1)
                .unwrap();

            let elem = TLVElement::new(wb.as_slice());
            assert_eq!(elem.tag().unwrap(), tag);
            assert_eq!(elem.u8().unwrap(), 1);
            assert_eq!(wb.as_slice().len(), 2 + tag.tag_type().size());
        }
    }

    #[test]
    fn debug_output_nests_builder_names() {
        let mut buf = [0; 16];
        let mut wb = WriteBuf::new(&mut buf);

        let arr = PairArrayBuilder::new(root(&mut wb), &TLVTag::Anonymous).unwrap();
        assert_eq!(format!("{arr:?}"), "\"root\"[]");

        let pair = arr.push().unwrap();
        assert_eq!(format!("{pair:?}"), "\"root\"[]::Pair<0>");

        let octets = pair.first(1).unwrap().second();
        assert_eq!(format!("{octets:?}"), "\"root\"[]::Pair<2>");
        drop(octets);

        wb.reset();
        let nullable =
            NullableBuilder::<_, ToTLVBuilder<Root, u8>>::new(root(&mut wb), &TLVTag::Anonymous);
        assert_eq!(format!("{nullable:?}"), "\"root\"");

        let arr = ToTLVArrayBuilder::<_, u8>::new(root(&mut wb), &TLVTag::Anonymous).unwrap();
        assert_eq!(format!("{arr:?}"), "\"root\"[]");
    }
}
