/*
 * Copyright (c) 2026 Project CHIP Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! A module for generating the event emitting utility code.
//! The actual layout of the event structs and builders are generated by the `struct_in` and `struct_out` modules.

use proc_macro2::{Literal, TokenStream};
use quote::quote;

use crate::idl::id::ident;
use crate::idl::parser::{EntityContext, Event, EventPriority};
use crate::IdlGenerateContext;

/// Return a token stream containing the structure definitions
/// for all structures in the given IDL cluster.
pub fn events(
    events: &[Event],
    entities: &EntityContext,
    context: &IdlGenerateContext,
) -> TokenStream {
    let events = events.iter().map(|e| event(e, entities, context));

    quote!(
        #(#events)*
    )
}

/// Creates the token stream corresponding to a structure
/// definition.
///
/// Provide the raw `struct Foo<'a>(TLVElement<'a>); impl<'a> Foo<'a> { ... }` declaration.
fn event(e: &Event, entities: &EntityContext, context: &IdlGenerateContext) -> TokenStream {
    let krate = context.rs_matter_crate.clone();

    let name = ident(&e.id);
    let name_builder = ident(&format!("{}Builder", &e.id));

    let priority = ident(match e.priority {
        EventPriority::Debug => "Debug",
        EventPriority::Info => "Info",
        EventPriority::Critical => "Critical",
    });

    let cluster_id = Literal::u64_unsuffixed(entities.cluster().unwrap().code);

    quote!(
        impl #name<'_> {
            const PRIORITY: #krate::im::EventPriority = #krate::im::EventPriority::#priority;

            pub fn emit_for<F>(emitter: impl #krate::dm::EventEmitter, endpoint_id: #krate::dm::EndptId, f: F) -> Result<#krate::dm::EventNumber, #krate::error::Error>
            where
                F: FnOnce(#name_builder<#krate::dm::events::EventTLVWrite<'_>>) -> Result<#krate::dm::events::EventTLVWrite<'_>, #krate::error::Error>,
            {
                emitter.emit_event(
                    endpoint_id,
                    #cluster_id,
                    EventId::#name as _,
                    Self::PRIORITY,
                    |tw| {
                        f(#name_builder::new(tw, &#krate::dm::events::EVENT_DATA_TAG)?)?;

                        Ok(())
                    },
                )
            }

            pub fn emit<F>(emitter: impl #krate::dm::OwnEventEmitter, f: F) -> Result<#krate::dm::EventNumber, #krate::error::Error>
            where
                F: FnOnce(#name_builder<#krate::dm::events::EventTLVWrite<'_>>) -> Result<#krate::dm::events::EventTLVWrite<'_>, #krate::error::Error>,
            {
                emitter.emit_own_event(
                    EventId::#name as _,
                    Self::PRIORITY,
                    |tw| {
                        f(#name_builder::new(tw, &#krate::dm::events::EVENT_DATA_TAG)?)?;

                        Ok(())
                    },
                )
            }
        }
    )
}
