name: PublishCrate

on:
  workflow_dispatch:
    inputs:
      crate:
        required: true
        type: choice
        description: Crate to publish
        options:
        - rs-matter-codegen
        - rs-matter-macros
        - rs-matter

env:
  rust_toolchain: stable

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rust-src
      - name: Login
        run: cargo login ${{ secrets.crates_io_token }}
      - name: Build | Publish
        run: cd "${{ github.event.inputs.crate }}"; cargo publish
